server:
  port: 8080
  servlet:
    context-path: /board-party/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_party?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root} # 示例账号
    password: ${DB_PASSWORD:123456} # 示例密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: ""